# Generated by Django 4.1.6 on 2023-09-27 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_newsletter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 6, 11, 29, 254192, tzinfo=datetime.timezone.utc)),
        ),
    ]
